### ISSUE TITLE
`dpp-plugin-option-merged is v:false`  does not work

### ISSUE THREAD

**Issue by qitoy** [Shougo/dpp.vim#25]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
I set non-lazy plugin `merged = false`, but plugin was merged.

## Expected
I do that, plugin is not merged (`.dpp` does not contain the plugin and `&rtp` contains the plugin).

## Environment Information

- dpp.vim version (SHA1): 976a0f193def5e1bc25ec4db2095c9c682584da7

- denops.vim version (SHA1): b1a21acec667d599c521ee5433f7363702b46694

- deno version(`deno -V` output): deno 1.44.4

- OS: NixOS 24.11.20240622.a71e967 (Vicuna) aarch64

- neovim/Vim `:version` output:
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
```

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

`/home/qitoy/.config/dpp_merged/init.vim`
```vim
let $BASE = '<script>:p:h'->expand()
const s:dpp_base = $BASE .. '/dpp'

function InitPlugin(plugin)
  let dir = s:dpp_base .. '/repos/github.com/' .. a:plugin
  execute 'set runtimepath^=' .. dir
endfunction

call InitPlugin('Shougo/dpp.vim')

if s:dpp_base->dpp#min#load_state()
  call InitPlugin('Shougo/dpp-protocol-git')
  call InitPlugin('vim-denops/denops.vim')

  call denops#server#wait_async({
  \-> dpp#make_state(s:dpp_base, '$BASE/config.ts'->expand())
  \})
endif
```

`/home/qitoy/.config/dpp_merged/config.ts`
```ts
import {
  BaseConfig,
  ConfigArguments,
  ConfigReturn,
} from "https://deno.land/x/dpp_vim@v0.3.0/types.ts";

export class Config extends BaseConfig {
  override config(args: ConfigArguments): ConfigReturn {
    args.contextBuilder.setGlobal({ protocols: ["git"] });
    return {
      plugins: [{
        repo: "vim-denops/denops.vim",
        name: "denops.vim",
        merged: false,
      }],
    };
  }
}
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `NVIM_APPNAME=dpp_merged nvim` twice

## Upload the log messages by `:redir` and `:message` (if errored)

after `NVIM_APPNAME=dpp_merged nvim`

`:echo &rtp`
```
/home/qitoy/.config/dpp_merged/dpp/repos/github.com/Shougo/dpp.vim,/home/qitoy/.config/dpp_merged,/home/qitoy/.config/dpp_merged/dpp/nvim/.dpp,/nix/store/k61lhzgn97r8z0qlxkjlcn33cfzblxd2-neovim-unwrapped-0.10.0/share/nvim/runtime,/nix/store/k61lhzgn97r8z0qlxkjlcn33cfzblxd2-neovim-unwrapped-0.10.0/share/nvim/runtime/pack/dist/opt/matchit,/nix/store/k61lhzgn97r8z0qlxkjlcn33cfzblxd2-neovim-unwrapped-0.10.0/lib/nvim,/home/qitoy/.config/dpp_merged/dpp/nvim/.dpp/after
```

`:echo dpp#get('denops.vim')`
```
{'rtp': '/home/qitoy/.config/dpp_merged/dpp/repos/github.com/vim-denops/denops.vim', 'lazy': v:false, 'name': 'denops.vim', 'repo': 'vim-denops/denops.vim', 'protocol': 'git', 'merged': v:true, 'sourced': v:true, 'path': '/home/qitoy/.config/dpp_merged/dpp/repos/github.com/vim-denops/denops.vim'} 
```

`$ ls dpp/nvim/.dpp/autoload`
```
denops  denops.vim  health
```

**Comment by Shougo** [comment]
OK.  I have fixed it.
