### ISSUE TITLE
`dpp#util#_clear_state` requires one argument, but called with no arguments.

### ISSUE THREAD

**Issue by Warashi** [Shougo/dpp.vim#6]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary

`dpp#util#_clear_state` requires one argument, but called with no arguments.

https://github.com/Shougo/dpp.vim/blob/d9f10f0710a3816e9aa132c610f82137df7a464a/autoload/dpp/util.vim#L152

https://github.com/Shougo/dpp.vim/blob/d9f10f0710a3816e9aa132c610f82137df7a464a/autoload/dpp/util.vim#L33
https://github.com/Shougo/dpp.vim/blob/d9f10f0710a3816e9aa132c610f82137df7a464a/autoload/dpp/min.vim#L19

I cannot provide configuration codes with problems around above codes, but this may causes problems.
So I submit this issue.

## Expected

called with required argument or make argument optional.

## Environment Information

- dpp.vim version (SHA1): d9f10f0710a3816e9aa132c610f82137df7a464a

- denops.vim version (SHA1):

- deno version(`deno -V` output):

- OS:

- neovim/Vim `:version` output:

## Provide a minimal init.vim/vimrc without plugin managers (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/dpp.vim/
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. foo
2. bar
3. baz

**Comment by Shougo** [comment]
Fixed.
